/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 scene.gltf 
Author: Robin Butler (https://sketchfab.com/StarTrekGuy)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/robobit-dex-3b5d15acb0de42f685d71686c651dcd8
Title: RoboBit - Dex
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Sphere_0.geometry}
        material={materials['Material.001']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.717}
      />
      <mesh
        geometry={nodes.Sphere_1.geometry}
        material={materials['Material.002']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.717}
      />
      <mesh
        geometry={nodes.Sphere_2.geometry}
        material={materials['Material.003']}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.717}
      />
    </group>
  )
}

useGLTF.preload('./models/scene-transformed.glb')
